### ISSUE TITLE
File name with space not supported

### ISSUE THREAD

**Issue by syl20lego** [mooz/node-pdf-image#13]
Missing a single quote for the outputImagePath (same as pdfFilePath)

return util.format(
      "convert %s'%s[%d]' '%s'",
      convertOptionString ? convertOptionString + " " : "",
      pdfFilePath, pageNumber, outputImagePath
    );

%s'%s[%d]' %s should be
%s'%s[%d]' '%s'

**Comment by syl20lego** [comment]
I notice this was part of a pull request already merged, can you republish the module to npm?

**Comment by mooz** [comment]
Sorry. I've republished the package with new version `v1.0.2`.

**Comment by syl20lego** [comment]
Great thanks a lot, I really appreciate it.
